"""add exercise detail columns

Revision ID: 8bdcc7fc327b
Revises: 94ae6777b010
Create Date: 2026-04-03 15:15:38.063642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bdcc7fc327b'
down_revision: Union[str, Sequence[str], None] = '94ae6777b010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('difficulty', sa.String(length=10), nullable=True))
    op.add_column('exercises', sa.Column('equipment', sa.String(length=50), nullable=True))
    op.add_column('exercises', sa.Column('youtube_url', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('met_value', sa.Numeric(precision=4, scale=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'met_value')
    op.drop_column('exercises', 'youtube_url')
    op.drop_column('exercises', 'equipment')
    op.drop_column('exercises', 'difficulty')
    op.create_table('notion_workout_log_raw',
    sa.Column('notion_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('kcal', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_edited_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('week_formula', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('time_min_rollup', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('exercise_rollup', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('category_rollup', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('muscle_rollup', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('exercise_log_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('synced_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('notion_id', name=op.f('notion_workout_log_raw_pkey'))
    )
    op.create_table('notion_exercise_log_raw',
    sa.Column('notion_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('exercise', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('sets', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('repeat', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('weight_kg', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('time_min', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('muscle', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('failed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_edited_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('week_rollup', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('workout_log_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('synced_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('notion_id', name=op.f('notion_exercise_log_raw_pkey'))
    )
    # ### end Alembic commands ###
